workflows:
  ios-ipa:
    name: iOS IPA (AltStore)
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Flutter clean & get
        script: |
          flutter clean
          flutter pub get

      - name: Build IPA (no signing)
        script: |
          flutter build ipa --release --no-codesign

    artifacts:
      - build/ios/ipa/*.ipa
